# Generated by Django 3.2.7 on 2022-02-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='popularity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
