# Generated by Django 3.2.7 on 2022-03-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_item_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='empty.jpg', upload_to=''),
        ),
    ]
