# Generated by Django 3.1.5 on 2021-06-18 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, default='Home', on_delete=django.db.models.deletion.RESTRICT, to='auctions.category'),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
