# Generated by Django 3.1.5 on 2021-06-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, default='Other', on_delete=django.db.models.deletion.RESTRICT, to='auctions.category'),
        ),
    ]
